In [2]:
data_preprocessed = pd.read_csv('Downloads/MUZO/DATA_ANALYTICS/Absenteeism_preprocessed.csv')

In [ ]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Downloads/MUZO/DATA_ANALYTICS/Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0                 30          0         2    1                          4  
1                 31          0         1    0                          0  
2                 31          0         0    0                          2  
3                 24          0         2    0                          4  
4                 30          0         2    1                          2  
..               ...        ...       ...  ...                        ...  
695               22          1         2    0                          8  
696               24          0         1    2                          3  
697               25          1         0    0                          8  
698               25          1         0    0                          2  
699               25          0         1    1                          2  

[700 rows x 15 columns]

In [4]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [5]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1           10                2   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            6                6   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            5                4   
20          1         0         0         0           12                1   
21          1         0         0         0            3                6   
22          1         0         0         0           10                3   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            4                2   
27          0         0         0         1           12                1   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
30          0         0         1         0            8                0   
31          0         0         1         0            8                3   
32          0         0         0         1            8                3   
33          0         0         1         0            8                0   
34          0         0         0         1            8                0   
35          0         0         0         1            8                0   
36          0         0         0         1            4                2   
37          1         0         0         0            8                3   
38          0         0         0         1            8                4   
39          0         0         0         1            8                4   
40          0         0         0         1            1                4   
41          0         0         0         1            7                3   
42          0         0         0         1            1                4   
43          0         0         1         0            8                6   
44          0         0         0         1            9                2   
45          0         0         0         1            9                6   
46          0         0         0         1            9                0   
47          0         0         0         1            9                3   
48          0         0         0         1            4                3   
49          1         0         0         0            9                0   
50          0         0         0         0            9                0   
5

In [6]:
#Regression model itself will give us a fair indication of which variables
#are important for analysis.Logistic regression is a type of classification
#We will create two classes, Moderately Absent and Excessively Absent

In [7]:
#Creatng Target. Everything below the median= normal, above = excessive
#Using the median as a cut-off line is numerically stable and rigid 

data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [8]:
#0s and 1s are our assigned targets. More than median= 1 and less=0

targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
                   

In [9]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [10]:
data_preprocessed['Excessive Absenteeism'] = targets

In [11]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [12]:
#Around 46% of Targets are 1s and around 54% are 0s

targets.sum() / targets.shape[0]

0.45571428571428574

In [13]:
#Dropping the Absenteeism column as we won't need it.

data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                           'Daily Work Load Average','Distance to Work'],axis=1)

In [14]:
data_with_targets is data_preprocessed

False

In [15]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                     289   33               30          0         2    1   
1                     118   50               31          0         1    0   
2                     179   38               31          0         0    0   
3                     279   39               24          0         2    0   
4                     289   33               30          0         2    1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [16]:
#Selecting inputs for our regression.We will use .iloc=used for selection
#(slicing) data by position when given rows and columns.

data_with_targets.shape

(700, 12)

In [18]:
#selecting inputs

unscaled_inputs = data_with_targets.iloc[:,:-1]

In [19]:
#Standardizing our data
#Scikit-learn is probably the most useful library for machine learning in 
#Python. The sklearn library contains a lot of efficient tools for machine
#learning and statistical modeling including classification, regression, 
#clustering and dimensionality reduction

In [20]:
#Data CORRECTION
#All features are standardized including Dummies
#When we standardize, we lose the whole interpretability of a dummy
#Commenting this code as we don't need it

#Absenteeism_scaler will be used to substract the mean and divide by the 
#standard deviation variablesie(featurewise.)

#from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler()

In [21]:
#Our custom scaler will not standardize all inputs, but only the ones we choose.
#In this way, we will be able to preserve the Dummies untouched.
#Best practice will have been to standardize prior to creating Dummies

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]
        

In [22]:
#We must choose the columns to be scaled. To see what we've got,
#We go back to the last checkpoint before we standardized.
#Checking the last checkpoint


unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [23]:
#Creating a new variable that will contain the features we wish to scale

#columns_to_scale = ['Transportation Expense','Month Value','Day of the Week', 
        #'Distance to Work','Age', 'Daily Work Load Average', 'Body Mass Index' 
        #,'Children', 'Pet']
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']        
        

In [24]:
##List comprehension is a syntactic construct which allows us to create
#a list from the existing lists based on loops,conditions..etc

columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [25]:
absenteeism_scaler = CustomScaler(columns_to_scale)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:67: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [26]:
absenteeism_scaler.fit(unscaled_inputs)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pet'],
             copy=None, with_mean=None, with_std=None)

In [27]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [28]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
5           0         0         0         1     0.929019   
6           0         0         0         1     0.030796   
7           0         0         0         1     0.030796   
8           0         0         1         0    -0.268611   
9           0         0         0         1     0.030796   
10          1         0         0         0     0.030796   
11          1         0         0         0     0.030796   
12          1         0         0         0     0.030796   
13          1         0         0         0     0.030796   
14          0         0         0         1     0.030796   
15          1         0         0         0     0.030796   
16          0         0         0         1     0.030796   
17          0         0         1         0     0.030796   
18          1         0         0         0     0.030796   
19          0         0         0         1    -0.568019   
20          1         0         0         0     1.527833   
21          1         0         0         0    -1.166834   
22          1         0         0         0     0.929019   
23          0         0         0         1     0.330204   
24          0         0         1         0     0.330204   
25          0         0         0         1     0.330204   
26          0         0         0         1    -0.867426   
27          0         0         0         1     1.527833   
28          0         0         1         0     0.330204   
29          0         0         0         1     0.330204   
30          0         0         1         0     0.330204   
31          0         0         1         0     0.330204   
32          0         0         0         1     0.330204   
33          0         0         1         0     0.330204   
34          0         0         0         1     0.330204   
35          0         0         0         1     0.330204   
36          0         0         0         1    -0.867426   
37          1         0         0         0     0.330204   
38          0         0         0         1     0.330204   
39          0         0         0         1     0.330204   
40          0         0         0         1    -1.765648   
41          0         0         0         1     0.030796   
42          0         0         0         1    -1.765648   
43          0         0         1         0     0.330204   
44          0         0         0         1     0.629611   
45          0         0         0         1     0.629611   
46          0         0         0         1     0.629611   
47          0         0         0         1     0.629611   
48          0         0         0         1    -0.867426   
49          1         0         0         0     0.629611   
50          0         0         0         0     0.629611   
51          0         0         0         0     0.629611   
52          0         0         0         1     0.330204   
53          0         0         0         1     0.629611   
54          0         0         0         0     0.629611   
55          0         0         0         0     0.629611   
56          0         0         1         0     0.629611   
57          0         0         0         1     0.629611   
58          0         0         0         0     0.629611   
59          0         0         0         1     1.228426   
60          0         0         0         1     0.629611   
61          0         0         0         1     0.629611   
62          0         0         0         1    -0.268611   
63          0         0         0         1     0.929019   
64          0         0         0         0     0.929019   
65          0         0         0         1  

In [29]:
scaled_inputs.shape

(700, 11)

In [30]:
#Overfitting occires when a model learns to predict the train data so well
#that it fails miserably on new data.We will split the data into train and 
#test, so we can asses he models accuracy on new data.

In [31]:
#Split the Data into train & test and shuffle.
#below model splits arrays or matrices into random train and test subsets.

from sklearn.model_selection import train_test_split

In [32]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 389         0         0         0         1    -1.466241   
 192         0         0         0         1     0.030796   
 657         0         0         1         0    -0.867426   
 678         0         0         0         1     0.629611   
 323         1         0         0         0     1.228426   
 534         1         0         0         0     0.330204   
 531         1         0         0         0     0.929019   
 232         0         0         0         1     0.629611   
 401         0         0         1         0    -1.166834   
 383         0         0         0         1    -1.466241   
 378         0         0         0         1    -1.466241   
 655         1         0         0         0    -1.466241   
 181         0         0         0         1    -1.166834   
 76          0         0         0         1     0.929019   
 653         0         0         0         1    -1.166834   
 359         0         0

In [33]:
#sklearn.mode_selection.train_test_split(inputs, targets,train_size,shuffle-True,random_state) splits arrays or 
#or matrices into random train and test subsets.

x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [34]:
#The inputs contains 175 observations along 14 input values
#The targets are a vector(a quantity possessing both magnitude and direction) of length 525.
#This contains 175 observations, 14 inputs and 1 target value/obervation

print(x_test.shape, y_test.shape)

(140, 11) (140,)


In [35]:
#The inputs contains 525 observations along 14 input values
#The targets are a vector(a quantity possessing both magnitude and direction) of length 525.
#This contains 525 observations, 14 inputs and 1 target value/obervation

print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [36]:
#75% of the observation will help us with training while 25% is testing.
#Usually, we opt for splits like 90-10 or 80-20 because we want to train on more data

In [37]:
#Logistic regression with Sklearn.Will import for machine learning 
#to tackle the mathematical issues.

from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [38]:
#Training the model

reg = LogisticRegression()

In [39]:
#Fit the model according to the given training data

reg.fit(x_train,y_train)

LogisticRegression()

In [40]:
#based in the data we used, our model learned to classify ~80%(0.78)
#of the observation correctly

reg.score(x_train,y_train)

0.7767857142857143

In [41]:
#Manually checking the accuracy

In [42]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [43]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [44]:
#comparing the elements of the two variable. Match = True

model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [45]:
#Finding the total number of true entries or matched entries

np.sum(model_outputs==y_train)

435

In [46]:
model_outputs.shape[0]

560

In [47]:
#If we divide the matches by total of entries,we get the ACCURACY

np.sum((model_outputs==y_train))/model_outputs.shape[0]


0.7767857142857143

In [48]:
#Finding the intercept and coefficients

reg.intercept_

array([-1.60957471])

In [49]:
reg.coef_

array([[ 2.77151176,  0.93168817,  3.09210221,  0.8090592 ,  0.00781237,
         0.62505482, -0.17390339,  0.28829409, -0.24081615,  0.35753531,
        -0.27337422]])

In [50]:
#We want to know what variable those coefficents refer to 

unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [51]:
#New variable containing all the unscaled values

feature_name = unscaled_inputs.columns.values

In [52]:
#Neat DataFrame containing the intercept, the feature and corresponding coefs
#We must transpose this array because by default, ndarrays are rows and not columns

summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table


Feature name  Coefficient
0                 Reason_1     2.771512
1                 Reason_2     0.931688
2                 Reason_3     3.092102
3                 Reason_4     0.809059
4              Month Value     0.007812
5   Transportation Expense     0.625055
6                      Age    -0.173903
7          Body Mass Index     0.288294
8                Education    -0.240816
9                 Children     0.357535
10                     Pet    -0.273374

In [53]:
#Adding the intercept.

summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table


Feature name  Coefficient
0                Intercept    -1.609575
1                 Reason_1     2.771512
2                 Reason_2     0.931688
3                 Reason_3     3.092102
4                 Reason_4     0.809059
5              Month Value     0.007812
6   Transportation Expense     0.625055
7                      Age    -0.173903
8          Body Mass Index     0.288294
9                Education    -0.240816
10                Children     0.357535
11                     Pet    -0.273374

In [54]:
#Interpreting the Coefficients

summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [55]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.609575    0.199973
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
3                 Reason_3     3.092102   22.023327
4                 Reason_4     0.809059    2.245794
5              Month Value     0.007812    1.007843
6   Transportation Expense     0.625055    1.868348
7                      Age    -0.173903    0.840378
8          Body Mass Index     0.288294    1.334150
9                Education    -0.240816    0.785986
10                Children     0.357535    1.429801
11                     Pet    -0.273374    0.760808

In [56]:
#Sort the DataFrame using the sort method.DataFrame.sort_values(Series)
#sorts the values in a DFwith respect to given column(Series)

summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.092102   22.023327
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
4                 Reason_4     0.809059    2.245794
6   Transportation Expense     0.625055    1.868348
10                Children     0.357535    1.429801
8          Body Mass Index     0.288294    1.334150
5              Month Value     0.007812    1.007843
7                      Age    -0.173903    0.840378
9                Education    -0.240816    0.785986
11                     Pet    -0.273374    0.760808
0                Intercept    -1.609575    0.199973

In [57]:
#Testing The ML model.Findng the accuracy in the same manner as before

reg.score(x_test,y_test)

0.7357142857142858

In [58]:
#So based on the new data,in 73.6% of the cases,the model will predict
#(correctly) if the person will be excessively absent
#The TEST accuracy is always less than the TRAIN accuracy by definition
#Often the test accuracy is 20-20% lower than the train(Due to Overfitting)

In [59]:
#Manually check the accuracy using probability.We use sklearn.linear
#_model.LogisticRegression.predict_proba(x)

predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75466347, 0.24533653],
       [0.60917591, 0.39082409],
       [0.48329093, 0.51670907],
       [0.75768232, 0.24231768],
       [0.08357741, 0.91642259],
       [0.3052464 , 0.6947536 ],
       [0.303675  , 0.696325  ],
       [0.11636888, 0.88363112],
       [0.7400284 , 0.2599716 ],
       [0.75596036, 0.24403964],
       [0.50609784, 0.49390216],
       [0.19501503, 0.80498497],
       [0.06248668, 0.93751332],
       [0.7055465 , 0.2944535 ],
       [0.29675526, 0.70324474],
       [0.52028649, 0.47971351],
       [0.50551315, 0.49448685],
       [0.50843643, 0.49156357],
       [0.36713074, 0.63286926],
       [0.06422143, 0.93577857],
       [0.73822433, 0.26177567],
       [0.75768232, 0.24231768],
       [0.47994423, 0.52005577],
       [0.47760936, 0.52239064],
       [0.22619725, 0.77380275],
       [0.74047815, 0.25952185],
       [0.51148533, 0.48851467],
       [0.87702735, 0.12297265],
       [0.24005377, 0.75994623],
       [0.75768232, 0.24231768],
       [0.

In [60]:
predicted_proba.shape

(140, 2)

In [61]:
#Probability of excess absenteeism(the probability of getting1).We slice
#out the last column.
predicted_proba[:,1] 


array([0.24533653, 0.39082409, 0.51670907, 0.24231768, 0.91642259,
       0.6947536 , 0.696325  , 0.88363112, 0.2599716 , 0.24403964,
       0.49390216, 0.80498497, 0.93751332, 0.2944535 , 0.70324474,
       0.47971351, 0.49448685, 0.49156357, 0.63286926, 0.93577857,
       0.26177567, 0.24231768, 0.52005577, 0.52239064, 0.77380275,
       0.25952185, 0.48851467, 0.12297265, 0.75994623, 0.24231768,
       0.38859882, 0.71238179, 0.69821485, 0.49507156, 0.24231768,
       0.59772596, 0.26042186, 0.78022686, 0.4398591 , 0.60641126,
       0.24188848, 0.49713003, 0.25862385, 0.40689715, 0.80759194,
       0.59889345, 0.71944702, 0.24317762, 0.24676126, 0.2414598 ,
       0.50180816, 0.29299268, 0.6947536 , 0.24459387, 0.82033268,
       0.39193844, 0.90599346, 0.26442957, 0.32150234, 0.3220128 ,
       0.70502976, 0.69623972, 0.26579672, 0.77584327, 0.24541121,
       0.24490372, 0.07551158, 0.26087263, 0.76176924, 0.29640101,
       0.25772789, 0.31539593, 0.88408057, 0.4387068 , 0.59547

In [62]:
#In reality,Logistic regression models calculate these probabilities
#in the backgorund. If proba <0.5 = 0 and if >0.5 = 1
#NEXT STEP SAVE OUR MODEL
#CREATE A MODEL
#GET new data,classify it,pass it through SQL
#ANALYZE in TABLEAU

In [63]:
#SAVING(Creating a file that will store the following info)
#This model is a Logistic Regression
#Coef =
#Intercept = 
#Random State = 20

#pickle[module]is a Python modle used to convert a Python object into
#a character stream.saving the reg variable into a file

In [68]:
import pickle

In [69]:
#We must save the absenteeism scaler too which was used to standardize
#all numerical variables

with open('model','wb') as file:
    pickle.dump(reg, file)

In [66]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)

In [67]:
#The second step of the DEPLOYMENT is about creating a mechanism to
#load the saved model and make presictions
#Storing code in a module will allow us to resuse it without trouble

In [3]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0                 30          0         2    1                          4  
1                 31          0         1    0                          0  
2                 31          0         0    0                          2  
3                 24          0         2    0                          4  
4                 30          0         2    1                          2  
..               ...        ...       ...  ...                        ...  
695               22          1         2    0                          8  
696               24          0         1    2                          3  
697               25          1         0    0                          8  
698               25          1         0    0                          2  
699               25          0         1    1                          2  

[700 rows x 15 columns]

In [4]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [5]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1           10                2   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            6                6   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            5                4   
20          1         0         0         0           12                1   
21          1         0         0         0            3                6   
22          1         0         0         0           10                3   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            4                2   
27          0         0         0         1           12                1   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
30          0         0         1         0            8                0   
31          0         0         1         0            8                3   
32          0         0         0         1            8                3   
33          0         0         1         0            8                0   
34          0         0         0         1            8                0   
35          0         0         0         1            8                0   
36          0         0         0         1            4                2   
37          1         0         0         0            8                3   
38          0         0         0         1            8                4   
39          0         0         0         1            8                4   
40          0         0         0         1            1                4   
41          0         0         0         1            7                3   
42          0         0         0         1            1                4   
43          0         0         1         0            8                6   
44          0         0         0         1            9                2   
45          0         0         0         1            9                6   
46          0         0         0         1            9                0   
47          0         0         0         1            9                3   
48          0         0         0         1            4                3   
49          1         0         0         0            9                0   
50          0         0         0         0            9                0   
5

In [6]:
#Regression model itself will give us a fair indication of which variables
#are important for analysis.Logistic regression is a type of classification
#We will create two classes, Moderately Absent and Excessively Absent

In [7]:
#Creatng Target. Everything below the median= normal, above = excessive
#Using the median as a cut-off line is numerically stable and rigid 

data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [8]:
#0s and 1s are our assigned targets. More than median= 1 and less=0

targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
                   

In [9]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [10]:
data_preprocessed['Excessive Absenteeism'] = targets

In [11]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [12]:
#Around 46% of Targets are 1s and around 54% are 0s

targets.sum() / targets.shape[0]

0.45571428571428574

In [13]:
#Dropping the Absenteeism column as we won't need it.

data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                           'Daily Work Load Average','Distance to Work'],axis=1)

In [14]:
data_with_targets is data_preprocessed

False

In [15]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                     289   33               30          0         2    1   
1                     118   50               31          0         1    0   
2                     179   38               31          0         0    0   
3                     279   39               24          0         2    0   
4                     289   33               30          0         2    1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [16]:
#Selecting inputs for our regression.We will use .iloc=used for selection
#(slicing) data by position when given rows and columns.

data_with_targets.shape

(700, 12)

In [17]:
#we will keep the first 14 columns.The last part of the code can either be
#[:,0:14] , [:,:14] or [:,0:-1]

data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1           10   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            6   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            5   
20          1         0         0         0           12   
21          1         0         0         0            3   
22          1         0         0         0           10   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            4   
27          0         0         0         1           12   
28          0         0         1         0            8   
29          0         0         0         1            8   
30          0         0         1         0            8   
31          0         0         1         0            8   
32          0         0         0         1            8   
33          0         0         1         0            8   
34          0         0         0         1            8   
35          0         0         0         1            8   
36          0         0         0         1            4   
37          1         0         0         0            8   
38          0         0         0         1            8   
39          0         0         0         1            8   
40          0         0         0         1            1   
41          0         0         0         1            7   
42          0         0         0         1            1   
43          0         0         1         0            8   
44          0         0         0         1            9   
45          0         0         0         1            9   
46          0         0         0         1            9   
47          0         0         0         1            9   
48          0         0         0         1            4   
49          1         0         0         0            9   
50          0         0         0         0            9   
51          0         0         0         0            9   
52          0         0         0         1            8   
53          0         0         0         1            9   
54          0         0         0         0            9   
55          0         0         0         0            9   
56          0         0         1         0            9   
57          0         0         0         1            9   
58          0         0         0         0            9   
59          0         0         0         1           11   
60          0         0         0         1            9   
61          0         0         0         1            9   
62          0         0         0         1            6   
63          0         0         0         1           10   
64          0         0         0         0           10   
65          0         0         0         1  

In [18]:
#selecting inputs

unscaled_inputs = data_with_targets.iloc[:,:-1]

In [19]:
#Standardizing our data
#Scikit-learn is probably the most useful library for machine learning in 
#Python. The sklearn library contains a lot of efficient tools for machine
#learning and statistical modeling including classification, regression, 
#clustering and dimensionality reduction

In [20]:
#Data CORRECTION
#All features are standardized including Dummies
#When we standardize, we lose the whole interpretability of a dummy
#Commenting this code as we don't need it

#Absenteeism_scaler will be used to substract the mean and divide by the 
#standard deviation variablesie(featurewise.)

#from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler()

In [21]:
#Our custom scaler will not standardize all inputs, but only the ones we choose.
#In this way, we will be able to preserve the Dummies untouched.
#Best practice will have been to standardize prior to creating Dummies

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]
        

In [22]:
#We must choose the columns to be scaled. To see what we've got,
#We go back to the last checkpoint before we standardized.
#Checking the last checkpoint


unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [23]:
#Creating a new variable that will contain the features we wish to scale

#columns_to_scale = ['Transportation Expense','Month Value','Day of the Week', 
        #'Distance to Work','Age', 'Daily Work Load Average', 'Body Mass Index' 
        #,'Children', 'Pet']
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']        
        

In [24]:
##List comprehension is a syntactic construct which allows us to create
#a list from the existing lists based on loops,conditions..etc

columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [25]:
absenteeism_scaler = CustomScaler(columns_to_scale)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:67: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [26]:
absenteeism_scaler.fit(unscaled_inputs)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pet'],
             copy=None, with_mean=None, with_std=None)

In [27]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [28]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
5           0         0         0         1     0.929019   
6           0         0         0         1     0.030796   
7           0         0         0         1     0.030796   
8           0         0         1         0    -0.268611   
9           0         0         0         1     0.030796   
10          1         0         0         0     0.030796   
11          1         0         0         0     0.030796   
12          1         0         0         0     0.030796   
13          1         0         0         0     0.030796   
14          0         0         0         1     0.030796   
15          1         0         0         0     0.030796   
16          0         0         0         1     0.030796   
17          0         0         1         0     0.030796   
18          1         0         0         0     0.030796   
19          0         0         0         1    -0.568019   
20          1         0         0         0     1.527833   
21          1         0         0         0    -1.166834   
22          1         0         0         0     0.929019   
23          0         0         0         1     0.330204   
24          0         0         1         0     0.330204   
25          0         0         0         1     0.330204   
26          0         0         0         1    -0.867426   
27          0         0         0         1     1.527833   
28          0         0         1         0     0.330204   
29          0         0         0         1     0.330204   
30          0         0         1         0     0.330204   
31          0         0         1         0     0.330204   
32          0         0         0         1     0.330204   
33          0         0         1         0     0.330204   
34          0         0         0         1     0.330204   
35          0         0         0         1     0.330204   
36          0         0         0         1    -0.867426   
37          1         0         0         0     0.330204   
38          0         0         0         1     0.330204   
39          0         0         0         1     0.330204   
40          0         0         0         1    -1.765648   
41          0         0         0         1     0.030796   
42          0         0         0         1    -1.765648   
43          0         0         1         0     0.330204   
44          0         0         0         1     0.629611   
45          0         0         0         1     0.629611   
46          0         0         0         1     0.629611   
47          0         0         0         1     0.629611   
48          0         0         0         1    -0.867426   
49          1         0         0         0     0.629611   
50          0         0         0         0     0.629611   
51          0         0         0         0     0.629611   
52          0         0         0         1     0.330204   
53          0         0         0         1     0.629611   
54          0         0         0         0     0.629611   
55          0         0         0         0     0.629611   
56          0         0         1         0     0.629611   
57          0         0         0         1     0.629611   
58          0         0         0         0     0.629611   
59          0         0         0         1     1.228426   
60          0         0         0         1     0.629611   
61          0         0         0         1     0.629611   
62          0         0         0         1    -0.268611   
63          0         0         0         1     0.929019   
64          0         0         0         0     0.929019   
65          0         0         0         1  

In [29]:
scaled_inputs.shape

(700, 11)

In [30]:
#Overfitting occires when a model learns to predict the train data so well
#that it fails miserably on new data.We will split the data into train and 
#test, so we can asses he models accuracy on new data.

In [31]:
#Split the Data into train & test and shuffle.
#below model splits arrays or matrices into random train and test subsets.

from sklearn.model_selection import train_test_split

In [32]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 389         0         0         0         1    -1.466241   
 192         0         0         0         1     0.030796   
 657         0         0         1         0    -0.867426   
 678         0         0         0         1     0.629611   
 323         1         0         0         0     1.228426   
 534         1         0         0         0     0.330204   
 531         1         0         0         0     0.929019   
 232         0         0         0         1     0.629611   
 401         0         0         1         0    -1.166834   
 383         0         0         0         1    -1.466241   
 378         0         0         0         1    -1.466241   
 655         1         0         0         0    -1.466241   
 181         0         0         0         1    -1.166834   
 76          0         0         0         1     0.929019   
 653         0         0         0         1    -1.166834   
 359         0         0

In [33]:
#sklearn.mode_selection.train_test_split(inputs, targets,train_size,shuffle-True,random_state) splits arrays or 
#or matrices into random train and test subsets.

x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [34]:
#The inputs contains 175 observations along 14 input values
#The targets are a vector(a quantity possessing both magnitude and direction) of length 525.
#This contains 175 observations, 14 inputs and 1 target value/obervation

print(x_test.shape, y_test.shape)

(140, 11) (140,)


In [35]:
#The inputs contains 525 observations along 14 input values
#The targets are a vector(a quantity possessing both magnitude and direction) of length 525.
#This contains 525 observations, 14 inputs and 1 target value/obervation

print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [36]:
#75% of the observation will help us with training while 25% is testing.
#Usually, we opt for splits like 90-10 or 80-20 because we want to train on more data

In [37]:
#Logistic regression with Sklearn.Will import for machine learning 
#to tackle the mathematical issues.

from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [38]:
#Training the model

reg = LogisticRegression()

In [39]:
#Fit the model according to the given training data

reg.fit(x_train,y_train)

LogisticRegression()

In [40]:
#based in the data we used, our model learned to classify ~80%(0.78)
#of the observation correctly

reg.score(x_train,y_train)

0.7767857142857143

In [41]:
#Manually checking the accuracy

In [42]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [43]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [44]:
#comparing the elements of the two variable. Match = True

model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [45]:
#Finding the total number of true entries or matched entries

np.sum(model_outputs==y_train)

435

In [46]:
model_outputs.shape[0]

560

In [47]:
#If we divide the matches by total of entries,we get the ACCURACY

np.sum((model_outputs==y_train))/model_outputs.shape[0]


0.7767857142857143

In [48]:
#Finding the intercept and coefficients

reg.intercept_

array([-1.60957471])

In [49]:
reg.coef_

array([[ 2.77151176,  0.93168817,  3.09210221,  0.8090592 ,  0.00781237,
         0.62505482, -0.17390339,  0.28829409, -0.24081615,  0.35753531,
        -0.27337422]])

In [50]:
#We want to know what variable those coefficents refer to 

unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [51]:
#New variable containing all the unscaled values

feature_name = unscaled_inputs.columns.values

In [52]:
#Neat DataFrame containing the intercept, the feature and corresponding coefs
#We must transpose this array because by default, ndarrays are rows and not columns

summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table


Feature name  Coefficient
0                 Reason_1     2.771512
1                 Reason_2     0.931688
2                 Reason_3     3.092102
3                 Reason_4     0.809059
4              Month Value     0.007812
5   Transportation Expense     0.625055
6                      Age    -0.173903
7          Body Mass Index     0.288294
8                Education    -0.240816
9                 Children     0.357535
10                     Pet    -0.273374

In [53]:
#Adding the intercept.

summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table


Feature name  Coefficient
0                Intercept    -1.609575
1                 Reason_1     2.771512
2                 Reason_2     0.931688
3                 Reason_3     3.092102
4                 Reason_4     0.809059
5              Month Value     0.007812
6   Transportation Expense     0.625055
7                      Age    -0.173903
8          Body Mass Index     0.288294
9                Education    -0.240816
10                Children     0.357535
11                     Pet    -0.273374

In [54]:
#Interpreting the Coefficients

summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [55]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.609575    0.199973
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
3                 Reason_3     3.092102   22.023327
4                 Reason_4     0.809059    2.245794
5              Month Value     0.007812    1.007843
6   Transportation Expense     0.625055    1.868348
7                      Age    -0.173903    0.840378
8          Body Mass Index     0.288294    1.334150
9                Education    -0.240816    0.785986
10                Children     0.357535    1.429801
11                     Pet    -0.273374    0.760808

In [56]:
#Sort the DataFrame using the sort method.DataFrame.sort_values(Series)
#sorts the values in a DFwith respect to given column(Series)

summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.092102   22.023327
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
4                 Reason_4     0.809059    2.245794
6   Transportation Expense     0.625055    1.868348
10                Children     0.357535    1.429801
8          Body Mass Index     0.288294    1.334150
5              Month Value     0.007812    1.007843
7                      Age    -0.173903    0.840378
9                Education    -0.240816    0.785986
11                     Pet    -0.273374    0.760808
0                Intercept    -1.609575    0.199973

In [57]:
#Testing The ML model.Findng the accuracy in the same manner as before

reg.score(x_test,y_test)

0.7357142857142858

In [58]:
#So based on the new data,in 73.6% of the cases,the model will predict
#(correctly) if the person will be excessively absent
#The TEST accuracy is always less than the TRAIN accuracy by definition
#Often the test accuracy is 20-20% lower than the train(Due to Overfitting)

In [59]:
#Manually check the accuracy using probability.We use sklearn.linear
#_model.LogisticRegression.predict_proba(x)

predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75466347, 0.24533653],
       [0.60917591, 0.39082409],
       [0.48329093, 0.51670907],
       [0.75768232, 0.24231768],
       [0.08357741, 0.91642259],
       [0.3052464 , 0.6947536 ],
       [0.303675  , 0.696325  ],
       [0.11636888, 0.88363112],
       [0.7400284 , 0.2599716 ],
       [0.75596036, 0.24403964],
       [0.50609784, 0.49390216],
       [0.19501503, 0.80498497],
       [0.06248668, 0.93751332],
       [0.7055465 , 0.2944535 ],
       [0.29675526, 0.70324474],
       [0.52028649, 0.47971351],
       [0.50551315, 0.49448685],
       [0.50843643, 0.49156357],
       [0.36713074, 0.63286926],
       [0.06422143, 0.93577857],
       [0.73822433, 0.26177567],
       [0.75768232, 0.24231768],
       [0.47994423, 0.52005577],
       [0.47760936, 0.52239064],
       [0.22619725, 0.77380275],
       [0.74047815, 0.25952185],
       [0.51148533, 0.48851467],
       [0.87702735, 0.12297265],
       [0.24005377, 0.75994623],
       [0.75768232, 0.24231768],
       [0.

In [60]:
predicted_proba.shape

(140, 2)

In [61]:
#Probability of excess absenteeism(the probability of getting1).We slice
#out the last column.
predicted_proba[:,1] 


array([0.24533653, 0.39082409, 0.51670907, 0.24231768, 0.91642259,
       0.6947536 , 0.696325  , 0.88363112, 0.2599716 , 0.24403964,
       0.49390216, 0.80498497, 0.93751332, 0.2944535 , 0.70324474,
       0.47971351, 0.49448685, 0.49156357, 0.63286926, 0.93577857,
       0.26177567, 0.24231768, 0.52005577, 0.52239064, 0.77380275,
       0.25952185, 0.48851467, 0.12297265, 0.75994623, 0.24231768,
       0.38859882, 0.71238179, 0.69821485, 0.49507156, 0.24231768,
       0.59772596, 0.26042186, 0.78022686, 0.4398591 , 0.60641126,
       0.24188848, 0.49713003, 0.25862385, 0.40689715, 0.80759194,
       0.59889345, 0.71944702, 0.24317762, 0.24676126, 0.2414598 ,
       0.50180816, 0.29299268, 0.6947536 , 0.24459387, 0.82033268,
       0.39193844, 0.90599346, 0.26442957, 0.32150234, 0.3220128 ,
       0.70502976, 0.69623972, 0.26579672, 0.77584327, 0.24541121,
       0.24490372, 0.07551158, 0.26087263, 0.76176924, 0.29640101,
       0.25772789, 0.31539593, 0.88408057, 0.4387068 , 0.59547

In [63]:
#SAVING(Creating a file that will store the following info)
#This model is a Logistic Regression
#Coef =
#Intercept = 
#Random State = 20

#pickle[module]is a Python modle used to convert a Python object into
#a character stream.saving the reg variable into a file

In [68]:
import pickle

In [69]:
#We must save the absenteeism scaler too which was used to standardize
#all numerical variables

with open('model','wb') as file:
    pickle.dump(reg, file)

In [66]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)

In [67]:
#The second step of the DEPLOYMENT is about creating a mechanism to
#load the saved model and make presictions
#Storing code in a module will allow us to resuse it without trouble